1 версия 6 ТЗ
Niks5041/java-kanban pull request #3
Opened 2024-04-14 21:32 UTC by Niks5041

2024-04-15 18:11 UTC, YazykovMikhail requested changes

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/HistoryManager.java
> +    ArrayList<Task> getHistory();
Используй интерфейсы в качестве типа перменных
List

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/HistoryManager.java
> +    void linkLast(Task task);
void linkLast(Task task);
    void removeNode(Node node);
    
    Эти два метода не нужно выносить в интерсфейс, они будут приватные, это внутреняя реализация

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +        if (t == null)
{} - обязательны по кодстайлу

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +        Node newNode = new Node(null, task, null);
Вместо этого кода:
```
        Node newNode = new Node(null, task, null);

        if (tail != null) {
            tail.next = newNode;
            newNode.prev = tail;
        }
        tail = newNode;

        if (head == null) {
            head = newNode;
        }
```
вызывай метод linkLast

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
```
    public void remove(int id) {
        Node node =  history.remove(id);
        if (node == null) {
            return;
        }
        removeNode(node);
       
    }
```
вот так будет получше

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(id)) {
вместо этого кода:
```
      if (history.containsKey(id)) {
            Node node = history.get(id);
            removeNode(node);
        }
```
просто вызывай remove(id) 
там уже будет проверка

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +    public void linkLast(Task task) {
```
	private void linkLast(Task task) {
		final Node node = new Node(task, last, null);
		if (head  == null) {
			head  = node;
		} else {
			tail.next = node;
		}
		tail = node;
	}
```

С учетом того что конструктор выглядит так:

```
	public Node(Task task, Node prev, Node next) {
			this.task = task;
			this.prev = prev;
			this.next = next;
		}
```

2024-04-15 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +        history.put(id, newNode);
ну и тут тогда будет:
		 history.put(id, tail);

2024-04-15 19:46 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/InMemoryHistoryManager.java
> +    public void linkLast(Task task) {
Серьезно я запутался конечно в этой логике

2024-04-15 19:50 UTC, Niks5041 commented
1. Добрый вечер, а почему радикальный?
3 дня мучался...
и все равно пока не 100% понимания
2. если в двух словах дадите коменты по по поводу логики узлов буду благодарен, суть то я понял вроде основную, но и ту не без помощи кода коллекции из идеи..
3. правильно, что я несоздаю новый пул?

2024-04-16 04:50 UTC, YazykovMikhail approved these changes

2024-04-16 17:36 UTC, merged