7 ТЗ 1 версия
Niks5041/java-kanban pull request #4
Opened 2024-04-25 17:36 UTC by Niks5041

7 тз 1 версия

2024-04-26 15:07 UTC, YazykovMikhail commented
Стоит добавить поле TaskType taskType в Task
или еще проще сделай метод для каждой задачи 
public TaskType getType() {
		return TaskType.TASK;
	}
который будет возвращать свой тип.

2024-04-26 15:08 UTC, YazykovMikhail commented
Теперь работа по умолчанию это:
	public static TaskManager getDefault() {
		return new FileBackedTaskManager(new File("resources/task.csv"));

2024-04-26 15:20 UTC, YazykovMikhail commented
Так же пропустилось, Сабтаска должна быть унаследована от Task, а у теьбя сейчас от Эпик.
Поправь на: 
public class Subtask extends Task {

2024-04-26 15:21 UTC, YazykovMikhail requested changes

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +        FileBackedTaskManager.task = task;
видимо осталось от какого то старого кода/версии, стоит убрать

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void deleteAllTasks() throws ManagerSaveException {
throws ManagerSaveException - Убери со всех методов, прокидывать их не нужно
исключение от RuntimeException прокидывать не нужно, это не обрабатываемые исключения, если оно случится значит в приложении ничего сделать нельзя, что бы поправить эту проблему

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void deleteAllTasks() throws ManagerSaveException {
Повтори работу с исключениями

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Throwable {
public class ManagerSaveException extends RuntimeException {

исключение сообщающие об ошибки и не требующие обязательной обратки стоит делать от RuntimeException

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void save() throws ManagerSaveException {
```
	protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(HEADER);
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
	}
```
Молодец что используешь буферизацию, но мы сохраняем все задачи, а не только Task
Так же обрати внимание, что перенос строки стоит делать стредствам ипрограммф, потому что в разных операционных системах он разный

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void save() throws ManagerSaveException {
Предварительно стоит сделать все поля в классе InMemoryTaskManager protected, что бы был прямой доступ у класса наследника

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private String convertToString(Task task) {
```
	public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```
будет попроще

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +            bW.write("id,type,name,status,description,epic" + "\n");
вынеси заголовок в статическую переменную HEADER
и лучше не делать в нем сразу перевод строки, все таки заголовок - это заголовок, там нет перевода строки, а кому нужен тот сам отдельно поставит

2024-04-26 15:21 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +     public FileBackedTaskManager loadFromFile(Path path) throws ManagerSaveException {
Если сипользовать стандартные методы добавления, то идентификаторы будут генерироваться заного, а нужно восстановить предыдущее состояние. 
Ведь в предыдущем состоянии могло быть 1,2,7,9 какие то заадчи быть удалены. 
Если восстанавливать в текущем методе, то их акутальные идентификаторы будут перетерты
И так же стоит нужно не забывать восстановить счетчик идентификторов на предыдущее значение

```
public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = CSVTaskFormat.taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```
Разбери код и можно переиспользовать

2024-04-26 16:33 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +        FileBackedTaskManager.task = task;
нет, просто компилятор не пропускал,может потому что наследовал от  Throwable

2024-04-26 16:34 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +package ru.yandex.javacource.alexandrov.schedule.exceptions;
а у меня и системных файлах и в идее она маленькая..
странно

2024-04-26 16:44 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void save() throws ManagerSaveException {
или лучше у наставника спросить

2024-04-26 18:25 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private String convertToString(Task task) {
TaskType.SUBTASK) ? task.getEpicId() : ""
вот это

2024-04-26 19:41 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +     public FileBackedTaskManager loadFromFile(Path path) throws ManagerSaveException {
а почему тут не надо использовать try with resourse?

2024-04-27 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private String convertToString(Task task) {
это сокращенный if, в ревью в том числе узнаешь что то новое

2024-04-27 16:00 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +     public FileBackedTaskManager loadFromFile(Path path) throws ManagerSaveException {
Можно считать через буферизацию и тогда можно использоать try with resourse, но методы класса Files, позволяют считывать данные и без этого

2024-04-27 16:02 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void save() throws ManagerSaveException {
Стоило написать вот так:
```
Молодец что используешь буферизацию. 
Но мы сохраняем все задачи, а не только Task
```
наоборот говорю что все верно сделал с буферизацией. Но сохранял не все задачи

2024-04-27 16:03 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    public void save() throws ManagerSaveException {
По поводу этого вопроса: 
```
а почему мы так делаем?
CSVTaskFormat
поему такому формат
```

Да тут я немного недосказал, сначала хотел тебе подскзаать что бы ты эти методы вынес в утлитный класс CSVTaskFormat и от туда вызывал статичекие методы, а потом уже когда смотрел дальше код, посмотрел что у тебя всего два метода и можно в целом оставить так. Немного рассинхронизировались подсказки, но сути не меняет.

2024-04-27 16:07 UTC, YazykovMikhail commented
оставлю еще отдельным сообещнием, что бы не пропустил 
![image](https://github.com/Niks5041/java-kanban/assets/92871393/d3ad86c1-2a4e-482b-a298-918541d74852)

2024-04-27 16:27 UTC, YazykovMikhail commented
Помечай поправленные комментарии как "решенные" и ты и ревьер будет видеть что ты поправил, а с чем остались вопросы

2024-04-27 16:27 UTC, YazykovMikhail requested changes

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +package ru.yandex.javacource.alexandrov.schedule.exceptions;
Странно, у меня она до сих пор большая

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +package ru.yandex.javacource.alexandrov.schedule.exceptions;
и в гете тоже 
![image](https://github.com/Niks5041/java-kanban/assets/92871393/7fa14bae-35eb-4a7b-911e-42bf13cda11f)

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +                writer.write(CSVTaskFormat.toString(task));
Немного друг друга недопоняли, либо используй метод 
convertToString который у тебя в текущем классе. 

Либо сделай утилитный класс CSVTaskFormat вынеси в него:
1) public static String convertToString(Task task) {
2)   public static Task convertFromString(String value) {
3)  public static final String HEADER = "id,type,name,status,description,epic";

и вызывай эти методы из утилитного класса вот таким образовм: 
CSVTaskFormat.convertToString(task);

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private static Task CSVTaskFormat;                 // почему именно так? не понимаю что с этим делать и тест не проходит
Стоит убрать, получилось недопонимание

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private final File file;                                   //а почему вы на File меняете, Я так понял, что Path выйгрышнее на сегодняшний день
В целом можно и Path, но файл мы считали и он уже хранится в классе и мы с ним работаем. 
И если файла нет, мы узнаем об этом при старте приложения

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +//        try (BufferedWriter bW = Files.newBufferedWriter(filePath, StandardCharsets.UTF_8)) {
Структура +- верная, но
1) переносы строк подходят не для каждой операционной системп
2) тут только оди задачи, без сабтасок

Если будет пустой Map то как раз нчиего ен будет, потому что цикл не запуститься, такие вещи можно проверять тестами

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +        int id = Integer.parseInt(split[0]);
Ты не используешь id задач, но их ты должен восстанавливать в том числе
Расширь/сдеоай новый констуктор для задач и созадвай задачи с id

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/TaskManager.java
> +    void deleteAllTasks() throws ManagerSaveException;
Стоит во всех методах убрать 
throws ManagerSaveException

2024-04-27 16:27 UTC, YazykovMikhail commented on test/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManagerTest.java
> +    void addInMemoryTaskManagerDifferentTypes() throws ManagerSaveException {
Стоит во всех тестах убрать 
throws ManagerSaveException

2024-04-27 16:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +                taskManager.addNewTask(task);                     //вы хотите, чтоб я метод универсальный создал? taskManager.addAnyTask(task);
этот метод может выглядить примерно вот так:

	protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}
лучше его сделать не в  taskManager, а тут же в FileBackedTaskManager. 
Как говорил использовать методы менеджера не очень, при восстановлении состояния, потому что они будут создавать нвоые id, а нам нужно именно восстановить старые. Для этого мы будет сохранять напрямую в хранилище, как покакзано в методе выше
В том числе поэтому мы делали protected поля в классе InMemoryTaskManager

2024-04-28 13:43 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Throwable {
я вот сделал изначально наследование от Throwable так как в тз просят сделать исключение IOException, а оно относится к проверяем, в Throwable и Eror ошибки наследуются,
 мне не понятно, как понять, какая ошибка может случится,
 плюс  вы же просите его наследовать от  RuntimeException, которые не проверяемые, эта задумка в чем заключается, я тз не понял, илил тут спецом так, но зачем тогда

2024-04-28 13:46 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private String convertToString(Task task) {
принял, условие изучил,
 но Task.getEpicId()  у таски нет такого метода он только у сабтаски же,
  я поэтому не придумав как вызвать его у задачи которая изначально Task, метод Subtask,
   может сделать статическим, или в таске сделать метод, чтобы тоже их получал, но странно вроде

2024-04-28 14:00 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +                writer.write(CSVTaskFormat.toString(task));
надеюсь верно вас понял, в save() поменял метод на конвертТуСтринг,
но тогда не очень понял, зачем нам private static Task CSVTaskFormat;

2024-04-28 14:01 UTC, Niks5041 commented on src/ru/yandex/javacource/Alexandrov/schedule/manager/FileBackedTaskManager.java
> +    private static Task CSVTaskFormat;                 // почему именно так? не понимаю что с этим делать и тест не проходит
я не нашел как отметить комментарий, поэтому, как в пачке глаза ставлю, что вопросов нет

2024-04-28 14:14 UTC, Niks5041 commented on test/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManagerTest.java
> +    void addInMemoryTaskManagerDifferentTypes() throws ManagerSaveException {
думал удалил...

2024-04-28 19:31 UTC, YazykovMikhail commented on src/ru/yandex/javacource/Alexandrov/schedule/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Throwable {
Там написано что нужно отлавливать IOException

`Исключения вида IOException нужно отлавливать внутри метода save и выкидывать собственное непроверяемое исключение ManagerSaveException`

2024-04-28 19:33 UTC, YazykovMikhail approved these changes

2024-04-28 19:40 UTC, merged