Sprint 8 solution time and duration
Niks5041/java-kanban pull request #5
Opened 2024-05-09 19:07 UTC by Niks5041

2024-05-10 07:33 UTC, YazykovMikhail requested changes

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
представляешь при вызове метода каждый раз нужно убдет сортировать заного все задачи. 
А вызываться он будет часто, при каждом мобнолении страници. 
Стоит сделать сразу насроить сортировку в списке и сразу добавлять туда задачи, когда ни приходят на добавление

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new HashSet<>();
protected final Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Соотвествено этот метод будет просто:
```
	public List<Task> getPrioritizedTasks() {
		return new ArrayList<>(prioritizedTasks);
	}
```

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public boolean checkValidation(Task task) {
вот как раз этот метод лучше сделать меодом доабвления в приоритет и проверки возможности добалвения:
```
	private void prioritize(Task task) {
		final LocalDateTime startTime = task.getStartTime();
		final LocalDateTime endTime = task.getEndTime();
		for (Task t : prioritizedTasks) {
			final LocalDateTime existStart = t.getStartTime();
			final LocalDateTime existEnd = t.getEndTime();
			if (!endTime.isAfter(existStart)) {// newTimeEnd <= existTimeStart
				continue;
			}
			if (!existEnd.isAfter(startTime)) {// existTimeEnd <= newTimeStart
				continue;
			}

			throw new TaskValidationException("Задача пересекаются с id=" + t.getId() + " c " + existStart + " по " + existEnd);
		}

		prioritizedTasks.add(task);
	}
```

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/TaskManager.java
> +    boolean checkValidation(Task task);
этот метод не нужно выносить в интерфес, это должен быт ьприватный метод, исключительно для внутренней логи. 
Ну и соотвественно теперь он будет чуть другой

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/tasks/Epic.java
> +    public LocalDateTime getEndTime() {
Класси с задачами - это просто классы для хранения/переноса данных, никакой бизнес логике тут не должно быть, а тем более зависимости от сервиса  InMemoryTaskManager. 
Представь что у тебя яблоко зависит от соковыжималки, тяжело такое представить, это соковыжималка зависит от яблок

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/tasks/Epic.java
> +    public LocalDateTime getEndTime() {
Этот метод стоит убрать и расчитывать время окнчания, так же как обновление статуса у Эпика

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
Вот тут по аналогии с обнолением статуса можно сделать обноление времени:
```
	private void updateEpicDuration(Epic epic) {
		List<Integer> subs = epic.getSubtaskIds();
		if (subs.isEmpty()) {
			epic.setDuration(0L);
			return;
		}
		LocalDateTime start = LocalDateTime.MAX;
		LocalDateTime end = LocalDateTime.MIN;
		long duration = 0L;
		for (int id : subs) {
			final Subtask subtask = subtasks.get(id);
			final LocalDateTime startTime = subtask.getStartTime();
			final LocalDateTime endTime = subtask.getEndTime();
			if (startTime.isBefore(start)) {
				start = startTime;
			}
			if (endTime.isAfter(end)) {
				end = endTime;
			}
			duration += subtask.getDuration();
		}
		epic.setDuration(duration);
		epic.setStartTime(start);
		epic.setEndTime(end);
	}
```

2024-05-10 07:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
И так же стоит обьеденить методы обновления статуса и времени в один метод:
```
	protected void updateEpic(int epicId) {
		Epic epic = epics.get(epicId);
		updateEpicStatus(epic);
		updateEpicDuration(epic);
	} 
```
Что бы потом вызывать только updateEpic там где раньще вызывался updateEpicStatuses

2024-05-11 18:43 UTC, Niks5041 commented on src/ru/yandex/javacource/alexandrov/schedule/manager/FileBackedTaskManager.java
> +                } catch (IOException e) {
у меня компилятор не пропускает без такой обработки

2024-05-11 18:53 UTC, Niks5041 commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
вроде по тз в коллекцию TreeSet просят завернуть или я не так понял

2024-05-11 19:46 UTC, Niks5041 commented on src/ru/yandex/javacource/alexandrov/schedule/tasks/Epic.java
> +    public LocalDateTime getEndTime() {
правильно я понял?
тогда мне в Task 
  public LocalDateTime getEndTime() {
        return startTime.plus(duration);
    }
    гетера достаточно для всех задач?
    а уже формирование самой переменной endTime я делаю благодаря обновлению продолжительности?
     в этом методе updateEpicDuration(Epic epic)
    в таком случае сложно представить себе это в реальности,
    вроде как епик изначально должен знать о своей продолжительности, а мы создаем метод для ее формирования, учитывая еще и подзадачи, на основе которых епик и формируется
    я поэтому и мучился в классе Epic что то сделать, и лучше чем  создать объект менеджера для создания самой задачи и получения ее поля, ничего не придумал

2024-05-11 20:29 UTC, Niks5041 commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public boolean checkValidation(Task task) {
@Override
    public boolean checkValidation(Task task) {
  if (prioritizedTasks.isEmpty()) {
            return false;
        }
        Optional<LocalDateTime> maxStartTime = prioritizedTasks.stream()
                .map(Task::getStartTime)
                .max(Comparator.comparing(taskStream -> taskStream));

        return task.getEndTime().isAfter(maxStartTime.get());
    }
    тут вот стрим просят и true false
    Реализуйте метод, который будет проверять, пересекаются ли две задачи по времени выполнения, и возвращать true или false. Для его реализации используйте математический метод наложения отрезков.
В методе add выполните проверку, пересекается ли добавляемая задача с любой другой в списке менеджера. Для этого используйте Stream API и метод, который вы реализовали в предыдущем пункте.
моя версия метода тут не уместна, не будет рабоать?

2024-05-12 06:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/tasks/Epic.java
> +    public LocalDateTime getEndTime() {
Эпик это например "Построить дом"
У него есть подзадачи
1) Залить фундамент
2) Возвести стены
3) Поставить крышу

Время эпика завивисит от подзадач. Он не может заранее знать о своей продолжительности, без подзазач, потому что фактически подзадачи это и есть его продолжительность

2024-05-12 06:46 UTC, YazykovMikhail requested changes

2024-05-12 06:46 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    private void prioritize(Task task) {
старайся приватные методы делать ниже публичных

2024-05-12 06:46 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +        for (Task t : prioritizedTasks) {                                         // а что лучше? for, как мы всегда делали или через стрим foreach
Однозначного ответа нет, бывают ситуации когда стримы и правда намного лучше, но тут нет разницы. 
В данном лсучае дело предпочтений

2024-05-12 06:46 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    protected void updateEpic(int epicId) {        // это задел для дальнейшей работы, или заменить уже везде?
Время эпика высчитывает в зависимости от его подзадач, следовательно всегда когда идут изменения в подзадачах, стоит вызывать метод актуализации времени Эпика. 
Со статусами эпика было так же, поэтому их можно обьеденить в один метод и вызывать везде, где раньше вызывался обновления статуса. 

Сейчас у тебя  updateEpicDuration не вызываетя нигде, нужно что бы вызывался во всех методах где изменяются сабтаски, что бы время Эпика просчитывалось автоматически, так же как и его статус, для этого мы обьеденили эти два метода в один, потому что вызываться они будет в одних и тек же местах. 
Стоит поправить

2024-05-12 06:46 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +        prioritize(task);                                     // если я правильно понял вас, в таком случае стрим уместен тогда, по тз просят?
Для эпика можно не использовать, потому что он будет использоватсья для сабтасок, а Эпик состоит из Сабтасок. 
Стрим используется тогда, когда он удобен и полезен.

2024-05-12 13:53 UTC, YazykovMikhail commented on src/ru/yandex/javacource/alexandrov/schedule/manager/InMemoryTaskManager.java
> +    public boolean checkValidation(Task task) {
Спасибо за комментарий, в ТЗ и правда есть нововведения, но сейчас у тебя хорошо сделано. И сказать четсно стримы - это не всегда хорошо

2024-05-12 13:53 UTC, YazykovMikhail approved these changes

2024-05-21 17:29 UTC, merged